# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/下载/public_LSRP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/下载/public_LSRP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/下载/public_LSRP/CMakeFiles /home/david/下载/public_LSRP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/下载/public_LSRP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LSRP

# Build rule for target.
LSRP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LSRP
.PHONY : LSRP

# fast build rule for target.
LSRP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/build
.PHONY : LSRP/fast

#=============================================================================
# Target rules for targets named lsrp

# Build rule for target.
lsrp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsrp
.PHONY : lsrp

# fast build rule for target.
lsrp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsrp.dir/build.make CMakeFiles/lsrp.dir/build
.PHONY : lsrp/fast

#=============================================================================
# Target rules for targets named test_toyexample

# Build rule for target.
test_toyexample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_toyexample
.PHONY : test_toyexample

# fast build rule for target.
test_toyexample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_toyexample.dir/build.make CMakeFiles/test_toyexample.dir/build
.PHONY : test_toyexample/fast

source/graph.o: source/graph.cpp.o
.PHONY : source/graph.o

# target to build an object file
source/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph.cpp.o
.PHONY : source/graph.cpp.o

source/graph.i: source/graph.cpp.i
.PHONY : source/graph.i

# target to preprocess a source file
source/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph.cpp.i
.PHONY : source/graph.cpp.i

source/graph.s: source/graph.cpp.s
.PHONY : source/graph.s

# target to generate assembly for a file
source/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph.cpp.s
.PHONY : source/graph.cpp.s

source/graph_io.o: source/graph_io.cpp.o
.PHONY : source/graph_io.o

# target to build an object file
source/graph_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph_io.cpp.o
.PHONY : source/graph_io.cpp.o

source/graph_io.i: source/graph_io.cpp.i
.PHONY : source/graph_io.i

# target to preprocess a source file
source/graph_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph_io.cpp.i
.PHONY : source/graph_io.cpp.i

source/graph_io.s: source/graph_io.cpp.s
.PHONY : source/graph_io.s

# target to generate assembly for a file
source/graph_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/graph_io.cpp.s
.PHONY : source/graph_io.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsrp.dir/build.make CMakeFiles/lsrp.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsrp.dir/build.make CMakeFiles/lsrp.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsrp.dir/build.make CMakeFiles/lsrp.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/mapf_util.o: source/mapf_util.cpp.o
.PHONY : source/mapf_util.o

# target to build an object file
source/mapf_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapf_util.cpp.o
.PHONY : source/mapf_util.cpp.o

source/mapf_util.i: source/mapf_util.cpp.i
.PHONY : source/mapf_util.i

# target to preprocess a source file
source/mapf_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapf_util.cpp.i
.PHONY : source/mapf_util.cpp.i

source/mapf_util.s: source/mapf_util.cpp.s
.PHONY : source/mapf_util.s

# target to generate assembly for a file
source/mapf_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapf_util.cpp.s
.PHONY : source/mapf_util.cpp.s

source/mapfaa_lsrp.o: source/mapfaa_lsrp.cpp.o
.PHONY : source/mapfaa_lsrp.o

# target to build an object file
source/mapfaa_lsrp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_lsrp.cpp.o
.PHONY : source/mapfaa_lsrp.cpp.o

source/mapfaa_lsrp.i: source/mapfaa_lsrp.cpp.i
.PHONY : source/mapfaa_lsrp.i

# target to preprocess a source file
source/mapfaa_lsrp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_lsrp.cpp.i
.PHONY : source/mapfaa_lsrp.cpp.i

source/mapfaa_lsrp.s: source/mapfaa_lsrp.cpp.s
.PHONY : source/mapfaa_lsrp.s

# target to generate assembly for a file
source/mapfaa_lsrp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_lsrp.cpp.s
.PHONY : source/mapfaa_lsrp.cpp.s

source/mapfaa_util.o: source/mapfaa_util.cpp.o
.PHONY : source/mapfaa_util.o

# target to build an object file
source/mapfaa_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_util.cpp.o
.PHONY : source/mapfaa_util.cpp.o

source/mapfaa_util.i: source/mapfaa_util.cpp.i
.PHONY : source/mapfaa_util.i

# target to preprocess a source file
source/mapfaa_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_util.cpp.i
.PHONY : source/mapfaa_util.cpp.i

source/mapfaa_util.s: source/mapfaa_util.cpp.s
.PHONY : source/mapfaa_util.s

# target to generate assembly for a file
source/mapfaa_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/mapfaa_util.cpp.s
.PHONY : source/mapfaa_util.cpp.s

source/search.o: source/search.cpp.o
.PHONY : source/search.o

# target to build an object file
source/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search.cpp.o
.PHONY : source/search.cpp.o

source/search.i: source/search.cpp.i
.PHONY : source/search.i

# target to preprocess a source file
source/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search.cpp.i
.PHONY : source/search.cpp.i

source/search.s: source/search.cpp.s
.PHONY : source/search.s

# target to generate assembly for a file
source/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search.cpp.s
.PHONY : source/search.cpp.s

source/search_astar.o: source/search_astar.cpp.o
.PHONY : source/search_astar.o

# target to build an object file
source/search_astar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_astar.cpp.o
.PHONY : source/search_astar.cpp.o

source/search_astar.i: source/search_astar.cpp.i
.PHONY : source/search_astar.i

# target to preprocess a source file
source/search_astar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_astar.cpp.i
.PHONY : source/search_astar.cpp.i

source/search_astar.s: source/search_astar.cpp.s
.PHONY : source/search_astar.s

# target to generate assembly for a file
source/search_astar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_astar.cpp.s
.PHONY : source/search_astar.cpp.s

source/search_dijkstra.o: source/search_dijkstra.cpp.o
.PHONY : source/search_dijkstra.o

# target to build an object file
source/search_dijkstra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_dijkstra.cpp.o
.PHONY : source/search_dijkstra.cpp.o

source/search_dijkstra.i: source/search_dijkstra.cpp.i
.PHONY : source/search_dijkstra.i

# target to preprocess a source file
source/search_dijkstra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_dijkstra.cpp.i
.PHONY : source/search_dijkstra.cpp.i

source/search_dijkstra.s: source/search_dijkstra.cpp.s
.PHONY : source/search_dijkstra.s

# target to generate assembly for a file
source/search_dijkstra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/search_dijkstra.cpp.s
.PHONY : source/search_dijkstra.cpp.s

source/union_find.o: source/union_find.cpp.o
.PHONY : source/union_find.o

# target to build an object file
source/union_find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/union_find.cpp.o
.PHONY : source/union_find.cpp.o

source/union_find.i: source/union_find.cpp.i
.PHONY : source/union_find.i

# target to preprocess a source file
source/union_find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/union_find.cpp.i
.PHONY : source/union_find.cpp.i

source/union_find.s: source/union_find.cpp.s
.PHONY : source/union_find.s

# target to generate assembly for a file
source/union_find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LSRP.dir/build.make CMakeFiles/LSRP.dir/source/union_find.cpp.s
.PHONY : source/union_find.cpp.s

test/test_toyexample.o: test/test_toyexample.cpp.o
.PHONY : test/test_toyexample.o

# target to build an object file
test/test_toyexample.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_toyexample.dir/build.make CMakeFiles/test_toyexample.dir/test/test_toyexample.cpp.o
.PHONY : test/test_toyexample.cpp.o

test/test_toyexample.i: test/test_toyexample.cpp.i
.PHONY : test/test_toyexample.i

# target to preprocess a source file
test/test_toyexample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_toyexample.dir/build.make CMakeFiles/test_toyexample.dir/test/test_toyexample.cpp.i
.PHONY : test/test_toyexample.cpp.i

test/test_toyexample.s: test/test_toyexample.cpp.s
.PHONY : test/test_toyexample.s

# target to generate assembly for a file
test/test_toyexample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_toyexample.dir/build.make CMakeFiles/test_toyexample.dir/test/test_toyexample.cpp.s
.PHONY : test/test_toyexample.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LSRP"
	@echo "... lsrp"
	@echo "... test_toyexample"
	@echo "... source/graph.o"
	@echo "... source/graph.i"
	@echo "... source/graph.s"
	@echo "... source/graph_io.o"
	@echo "... source/graph_io.i"
	@echo "... source/graph_io.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/mapf_util.o"
	@echo "... source/mapf_util.i"
	@echo "... source/mapf_util.s"
	@echo "... source/mapfaa_lsrp.o"
	@echo "... source/mapfaa_lsrp.i"
	@echo "... source/mapfaa_lsrp.s"
	@echo "... source/mapfaa_util.o"
	@echo "... source/mapfaa_util.i"
	@echo "... source/mapfaa_util.s"
	@echo "... source/search.o"
	@echo "... source/search.i"
	@echo "... source/search.s"
	@echo "... source/search_astar.o"
	@echo "... source/search_astar.i"
	@echo "... source/search_astar.s"
	@echo "... source/search_dijkstra.o"
	@echo "... source/search_dijkstra.i"
	@echo "... source/search_dijkstra.s"
	@echo "... source/union_find.o"
	@echo "... source/union_find.i"
	@echo "... source/union_find.s"
	@echo "... test/test_toyexample.o"
	@echo "... test/test_toyexample.i"
	@echo "... test/test_toyexample.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

